{% set version = '2.0.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cluster
  version: {{ version|replace("-", "_") }}

source:
  fn: cluster_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/cluster_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/cluster/cluster_{{ version }}.tar.gz
  sha256: f424b87f10595ed358b1ac80471b520ab9c767a4d203663c25b177c8ce5f8ffc

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('cluster')"  # [not win]
    - "\"%R%\" -e \"library('cluster')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=cluster
  license: GPL (>= 2)
  summary: Methods for Cluster analysis.  Much extended the original from Peter Rousseeuw, Anja
    Struyf and Mia Hubert, based on Kaufman and Rousseeuw (1990) "Finding Groups in
    Data".
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
