appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: A5ZDO4qNnp3pS77Y+gIKLY5Hv3zcWbMvoAght4pez0tQAxEffX3uB934to/dmkwqcxDwzT1HiC8cuDKwWkd3OJAn+nN7leLUSDRsgm641CGMy042ySte0ohbVlxnaRm064kYv/jV2cWVXu8FyqY5tWAndps5UgmW9f+Umdzb4mm1Zjkkmnx6Xgxd/yQwPFMI4rn1drQDeHpRvITiHW6fbDnLHWSMwFO8GpULaAFkJYZO5JVORvOGCDwjEaXusWXlfp8XXSsl67jI0In1i6GQPFLOLIDTF1ftaMNv8tb4XXtkqQhXaWL8nu9bS6oeFZRG0NNKjKpC7y0+6TLBIV3flJYUCbQh4PwExAb+6ZDVYqs+KSeVlVJxzH/41/l0UnqprTMatQGv0qvEtwRJgtmWcyZrvqhrhzPDSphGa8/2A21nIGSkQya6iVa7S65rkb5trZD+Ddt2WIFSMDBYtwUPScwMJt4lYMvZZfpjdRkIRUKniBdaRaGgC3RfLhbqogmOWc8W9atSVQSzj3IW7dwdx152HBlPMeEPp0mRZXqt9Ap15n1sdcx9rEjG019A3HxSmtg9BrsnwWvWiWImJPnbc7YojRlH4sAbli5rmC6JgfFgKXkwzNONMvpXzM8Ln7EFDxlAB48P3Ik9riNlxBX7ISIr1Uqsgru1kU2te3g4pz4=}
bot:
  automerge: true
